services:
  blog-frontend:
    image: blog-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    container_name: blog-frontend-dev
  blog-backend:
    image: blog-back-dev
    volumes:
      - ./backend/:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-blog
    depends_on:
      - blog-frontend
      - blog-backend
